[package]
name = "risingwave_expr"
description = "Core expression traits and function registry."
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-hack", "ctor"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack", "ctor"]

[dependencies]
anyhow = "1"
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
async-trait = "0.1"
auto_impl = "1"
await-tree = { workspace = true }
cfg-or-panic = "0.2"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
ctor = "0.2"
downcast-rs = "1.2"
easy-ext = "1"
either = "1"
futures-async-stream = { workspace = true }
futures-util = "0.3"
itertools = "0.11"
num-traits = "0.2"
parse-display = "0.8"
paste = "1"
risingwave_common = { workspace = true }
risingwave_expr_macro = { path = "../macro" }
risingwave_pb = { workspace = true }
risingwave_udf = { workspace = true }
smallvec = "1"
static_assertions = "1"
thiserror = "1"
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
expect-test = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt-multi-thread",
    "macros",
] }

[lints]
workspace = true
