[package]
name = "risingwave_planner_test"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
expect-test = "1"
itertools = "0.11"
paste = "1"
risingwave_expr_impl = { workspace = true }
risingwave_frontend = { workspace = true }
risingwave_sqlparser = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_with = "3"
serde_yaml = "0.9"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
walkdir = "2"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
libtest-mimic = "0.6"
tempfile = "3"

[lib]
test = false

[[test]]
name = "planner_test_runner"
harness = false

[lints]
workspace = true
