[package]
name = "risingwave_java_binding"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
jni = "0.21.1"
prost = "0.11"
risingwave_common = { workspace = true }
risingwave_jni_core = { workspace = true }
risingwave_pb = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
risingwave_expr = { workspace = true }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "data-chunk-payload-generator"
test = false
bench = false

[[bin]]
name = "data-chunk-payload-convert-generator"
test = false
bench = false

[lints]
workspace = true
