[package]
name = "risingwave_storage"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
arc-swap = "1"
async-trait = "0.1"
auto_enums = { version = "0.8", features = ["futures03"] }
await-tree = { workspace = true }
bytes = { version = "1", features = ["serde"] }
crossbeam = "0.8.2"
dashmap = { version = "5", default-features = false }
dyn-clone = "1.0.14"
either = "1"
enum-as-inner = "0.6"
fail = "0.5"
foyer = { git = "https://github.com/mrcroxx/foyer", rev = "41b1d39" }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
hex = "0.4"
itertools = "0.11"
libc = "0.2"
lz4 = "1.24.0"
memcomparable = "0.2"
more-asserts = "0.3"
num-integer = "0.1"
parking_lot = "0.12"
prometheus = { version = "0.13", features = ["process"] }
prost = "0.11"
rand = "0.8"
risingwave_backup = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_service = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_hummock_trace = { workspace = true }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
scopeguard = "1"
sled = "0.34.7"
spin = "0.9"
sync-point = { path = "../utils/sync-point" }
tempfile = "3"
thiserror = "1"
# tikv-client = { git = "https://github.com/tikv/client-rust", rev = "5714b2", optional = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tonic = { workspace = true }
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["futures-03"] }
xorf = "0.8.1"
xxhash-rust = { version = "0.8.7", features = ["xxh32", "xxh64"] }
zstd = { version = "0.12", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.15", default-features = false }
libc = "0.2"
nix = { version = "0.27", features = ["fs", "mman"] }

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { git = "https://github.com/risingwavelabs/darwin-libproc.git", rev = "a502be24bd0971463f5bcbfe035a248d8ba503b7" }
libc = "0.2.148"
mach2 = "0.4"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_futures"] }
moka = { version = "0.12", features = ["future"] }
risingwave_test_runner = { workspace = true }
uuid = { version = "1", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
fiemap = "0.1.1"

[features]
# rocksdb-local = ["rocksdb"]
# tikv = ["tikv-client"]
test = []
failpoints = ["fail/failpoints"]
bpf = []
hm-trace = []

[[bench]]
name = "bench_block_iter"
harness = false
# Enable debug if you want to generate flamegraph.
# debug = true

[[bench]]
name = "bench_lru_cache"
harness = false

[[bench]]
name = "bench_merge_iter"
harness = false

[[bench]]
name = "bench_fs_operation"
harness = false

[[bench]]
name = "bench_compression"
harness = false

[[bench]]
name = "bench_compactor"
harness = false

[[bench]]
name = "bench_multi_builder"
harness = false

[[bench]]
name = "bench_row"
harness = false

[lints]
workspace = true
