name: Hakari Fix

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths: ["Cargo.lock", "**/Cargo.toml"]

jobs:
  hakari-fix:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install cargo-hakari
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hakari

      - name: Hakari generate
        run: cargo hakari generate

      - name: Show diff
        run: git diff

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix "cargo-hakari"
